Development - Pedram
NeidenThump/Spelifierad-bordtennis-TNM094 pull request #2
Opened 2024-06-12 13:08 UTC by Pedram45

Har lagt till fler måltavlor, det går att ändra antalet genom att ändra på variabeln. Måltavlorna är även lite mindre. De ska heller inte överlappa varandra. 
Har lagt till en useSimulation på matlab för att kunna växla mellan att använda simulerade bollstuds och mikrofonerna.

2024-06-12 17:59 UTC, ResearchDaniel requested changes

2024-06-12 17:59 UTC, ResearchDaniel commented on _MATLAB/positionCalc.m
> +%soundMicD = bandpass(soundMicD,[7500, 8500], Fs);
Vet inte riktigt hur kommenteringen hänger ihop med måltavlorna. Generellt: Ta bort bortkommenterad kod.

2024-06-12 17:59 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +	int width = 300;	//Made the targets smaller.
Kommentaren passar nog bättre som ett commit-meddelande.

2024-06-12 17:59 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +			//std::cout << "incoming X: " << coordinates.first << ", incoming Y: " << coordinates.second << std::endl;
Ta bort debug-kod

2024-06-12 17:59 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +			// Render m�ltavla
Är filen inte sparad i UTF-8? Konstiga tecken för åäö...

2024-06-12 17:59 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +					for (int j = 0; j < NUM_TARGETS; ++j) {
Duplicerad kod. Refaktorera till en hjälpfunktion

2024-06-12 17:59 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +				// Render all targets again after repositioning one
Varför rendera igen?  Det görs väl nästa frame?

2024-06-12 17:59 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +					continue; //Potential bug: continue should continue the outer while loop, not inner for loop.
?

2024-06-12 18:43 UTC, Pedram45 commented on _MATLAB/positionCalc.m
> +%soundMicD = bandpass(soundMicD,[7500, 8500], Fs);
Detta var ifall man skulle använda 4 mikrofoner. Har tagit bort den kommentaren.

2024-06-12 18:43 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +	int width = 300;	//Made the targets smaller.
Har tagit bort den kommentaren, finns redan skrivet som ett commit-meddelande.

2024-06-12 18:43 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +			//std::cout << "incoming X: " << coordinates.first << ", incoming Y: " << coordinates.second << std::endl;
Har tagit bort denna debug-kod.

2024-06-12 18:44 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +			// Render m�ltavla
Vet inte varför den gör så, programmet körs som vanligt, men har ändrat texten.

2024-06-12 18:44 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +					for (int j = 0; j < NUM_TARGETS; ++j) {
Var exakt menar du? Förstår inte riktigt.

2024-06-12 18:44 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +				// Render all targets again after repositioning one
Om inte detta görs så blinkar måltavlorna, alltså att alla försvinner och sedan kommer tillbaka. När man flyttar på måltavlans position måste man rendera om alla, annars försvinner de tills nästa frame.

2024-06-12 18:44 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +					continue; //Potential bug: continue should continue the outer while loop, not inner for loop.
Det var ett problem innan men glömde att ta bort kommentaren, det ska fungera.

2024-06-12 19:00 UTC, ResearchDaniel commented on _MATLAB/positionCalc.m
> +%if(deltaTAB < 0)
Fortfarande en massa bortkommenterad kod här

2024-06-12 19:00 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +					for (int j = 0; j < NUM_TARGETS; ++j) {
Ungefär samma kod finns på annat ställe:
```
			// Check if the new target position overlaps with any existing targets
			for (int j = 0; j < i; ++j) {
				if (targetsOverlap(targets[i].x, targets[i].y, targets[j].x, targets[j].y, width)) {
					validPosition = false; // Set flag to false if overlap is detected
					break; // Exit the inner loop if an overlap is found
				}
			}
		} while (!validPosition); // Repeat until a valid position is found
```

Du skulle kunna refaktorera denna kod för att undvika att samma kod är skriven på flera olika ställen

2024-06-12 19:00 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +				// Render all targets again after repositioning one
Blinkar alla? I så fall kanske det har något att göra med att SDL_RenderClear kallas i loopen?
Kanske är enklare om du separerar logiken för att se ifall en måltavla är träffad och att rendera dem

2024-06-12 20:27 UTC, Pedram45 commented on _MATLAB/positionCalc.m
> +%if(deltaTAB < 0)
Denna kod ska användas när mikrofonerna ska användas, men har lagt till en växel för att kunna växla mellan simulation och mikrofonerna.

2024-06-12 20:27 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +				// Render all targets again after repositioning one
Den här koden är från den förra versionen som jag inte har skrivit och jag vågar inte ändra på den eftersom jag inte vet hur det kommer påverka resten av koden.
Detta skulle förmodligen behöva mycket refaktorering eftersom det finns andra delar som påverkas av det.

2024-06-12 20:27 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +					for (int j = 0; j < NUM_TARGETS; ++j) {
Jag har lagt till en ny funktion som fixar detta.

2024-06-13 12:08 UTC, ResearchDaniel requested changes
Koden för att rendera verkar konstig och är nog källan till varför det blinkar. Kolla dokumentationen för SDL_XYZ-funktionerna gör och se till att koden som använder dem är rimlig

2024-06-13 12:08 UTC, ResearchDaniel commented on _MATLAB/positionCalc.m
> +    Define anonymous functions for hyperbolas
% Define...

2024-06-13 12:08 UTC, ResearchDaniel commented on _MATLAB/positionCalc.m
> +end
ingen else?

2024-06-13 12:08 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +void findEmptyTargetSpace(int& targetX, int& targetY, std::vector<SDL_Point>targets, int targetWidth, SDL_Rect secondDisplayBounds, const int NUM_TARGET) {
Returnera `std::array<int, 2>` eller liknande istället för att skriva till argumenten

2024-06-13 12:08 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +		//RenderRectangle_target(Topleft_x(x, width/2), Topleft_y(y, hight/2), width, hight, 255);
Ta bort kommenterad kod

2024-06-13 12:08 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +				// Render all targets again after repositioning one
Läs dokumentation om SDL_RenderClear
https://wiki.libsdl.org/SDL2/SDL_RenderClear

Den rensar hela bilden och du gör det varje gång spelaren träffar målet, vilket säkert resulterar i blinkningar. Det borde bara göras en gång i början av renderingen. Du får gå igenom koden för att rendera och se till att den är rimlig.

2024-06-14 15:06 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +				// Render all targets again after repositioning one
Har försökt att fixa detta genom att flytta så att det endast renderas en gång i början, den slutade blinka då, men det som hände var att den måltavla som blev träffad hann inte försvinna innan den nya på den nya positionen syndes. Ska jag försöka lösa det på andra sätt?

2024-06-14 15:07 UTC, Pedram45 commented on _MATLAB/positionCalc.m
> +    Define anonymous functions for hyperbolas
FIxat detta.

2024-06-14 15:07 UTC, Pedram45 commented on _MATLAB/positionCalc.m
> +end
Har lagt till en else.

2024-06-14 15:07 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +void findEmptyTargetSpace(int& targetX, int& targetY, std::vector<SDL_Point>targets, int targetWidth, SDL_Rect secondDisplayBounds, const int NUM_TARGET) {
Har ändrat till att det är array som beskrivet, och ändrat lite annan kod också för att det skulle fungera.

2024-06-14 15:07 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +		//RenderRectangle_target(Topleft_x(x, width/2), Topleft_y(y, hight/2), width, hight, 255);
Har tagit bort den koden.

2024-06-14 15:50 UTC, ResearchDaniel commented on src/spelmotor/main.cpp
> +				// Render all targets again after repositioning one
Det är troligtvis för att du renderar dem två gånger?
Kanske är enklast att skissa upp vad som bör hända i vilken ordning och sedan implementera det.

2024-06-15 09:24 UTC, Pedram45 commented on src/spelmotor/main.cpp
> +				// Render all targets again after repositioning one
Har läst igenom dokumentationen och kollat igenom koden igen, och har hittat orsaken. Det var som du sa, alltså att den renderades för många gånger. Har nu delat upp logiken i två delar genom att göra två funktioner, renderGame och handleHits. En för att hantera träffarna och en för renderingen. Detta gör att vi slipper överflödiga renderingar. handleHits uppdaterar måltavlornas positioner och deras poäng. renderGame rensar renderaren, renderar sedan poängen, måltavlorna och bollstudsens animering. Dessa funktioner anropas i game loopen.

2024-06-17 09:14 UTC, ResearchDaniel approved these changes
Ser mycket bättre ut nu!
Redo att sammanfogas med main-grenen tycker jag.

2024-06-17 11:25 UTC, merged